version: "3.8"

services:

  bot:
    container_name: arch-bot
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-data:/data
    ports:
      - '27017:27017'
    logging:
      driver: none

volumes:
  mongo-data:
