version: "3.8"

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: arch:bot-prod
    restart: unless-stopped
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-data:/data
    logging:
      driver: none

volumes:
  mongo-data:
